log_path: log/

coser-service:
  dataset_hf: "cladsu/COSER-2024"
  local_dataset: "data/CLEAN_df_hack_full.csv"

prompt_input:
  openai_key: YOUR_OPEN_AI_KEY
  model: google/flan-t5-base
  task: locations
  input: "A continuación vas a recibir una lista de peticiones: \n {}\n Dame una lista con peticiones similares. "
  out_folder: ./prompts_locations

locations:
  dataset_hf: "cladsu/COSER-2024"
  input_prompts: 
    - "A continuación vas a recibir una entrevista en la que pueden participar varios entrevistadores (E), indicados como E1, E2, ..., y varios informadores (I), indicados como I1, I2, sucesivamente. Basándote en los rasgos lingüísticos mostrados por los informadores, determina la provincia española a la que pertenecen."
    - "Dime la provincia del siguiente texto basándose en sus características lingüísticas. Texto:"
    - "Dime la provincia del siguiente texto:"
    - "Con la información de la siguiente entrevista, dame el lugar al que pertenecen los hablantes: "
    - "Dime de qué lugar es el siguiente texto:"