log_path: log/

coser_service:
  dataset_hf: "cladsu/COSER-2024"
  local_dataset: "data/CLEAN_df_hack_full.csv"
  out_prompt_folder: "data/out_prompts"

prompt_input:
  openai_key: YOUR_OPEN_AI_KEY
  model: google/flan-t5-base
  task: locations
  input: "A continuación vas a recibir una lista de peticiones: \n {}\n Dame una lista con peticiones similares. "
  out_folder: ./prompts_locations

locations:
  dataset_hf: "cladsu/COSER-2024"
  out_folder: "data/locations"
  input_prompts: 
    - "A continuación vas a recibir una entrevista en la que pueden participar varios entrevistadores (E), indicados como E1, E2, ..., y varios informadores (I), indicados como I1, I2, sucesivamente. Basándote en los rasgos lingüísticos mostrados por los informadores, determina la provincia española a la que pertenecen. {}"
    - "Dime la provincia del siguiente texto basándose en sus características lingüísticas. Texto: {}"
    - "Dime la provincia del siguiente texto: {}"
    - "Con la información de la siguiente entrevista, dame el lugar al que pertenecen los hablantes: {}"
    - "Dime de qué lugar es el siguiente texto:  {}"
  
  output_prompts:
    - "La provincia a la que pertenecen los informadores es {}."
    - "{} es la procedencia de los informadores en esta entrevista."
    - "La provincia española a la que pertenece a los informadores de la entrevista, según sus rasgos lingüísticos, es {}."
    - "La provincia española a la que pertenecen los informadores es {}."
    - "Según su acento y vocabulario, los informadores son oriundos de {}."
    - "La provincia española a la que pertenecen los informadores en esta entrevista es {}."
    - "La provincia de origen de los informadores en esta entrevista es {}."
    - "El origen geográfico de los informadores en esta entrevista se encuentra en {}."
    - "Los informadores de la entrevista son de {}, según su estilo lingüístico."
    - "La provincia española a la que pertenece el informant en la entrevista, según sus rasgos lingüísticos, es {}."
    - "Los informadores de la entrevista son característicos de la provincia de {}."
    - "La procedencia de los informadores, según su modo de expresarse, es {}."
    - "El lenguaje de los informadores de la entrevista indica que pertenecen a la provincia de {}, España."
    - "El lenguaje de los informadores de la entrevista indica que pertenecen a la provincia de {}, en España."
    - "La procedencia geográfica de los informadores se evidencia por su dialecto, propio de {}."
    - "Los informadores entrevistados muestran características lingüísticas propias de {}."
    - "{} es la localidad de la que proceden los informadores de esta entrevista."
    - "La provincia de {} es la región de la que proceden los informadores entrevistados."
    - "Los informadores presentan patrones lingüísticos asociados con {}, según se desprende de la entrevista."
    - "Se puede inferir que los informadores son de {} basándose en su lenguaje durante la entrevista."
    - "Los informadores en esta entrevista tienen un habla que los sitúa en {}."
    - "¡Claro! Basándome en los datos proporcionados, puedo determinar que el informante belongs a la provincia de {}."
    - "En esta entrevista, los informadores provienen de {}."
    - "Basándome en los datos proporcionados, la provincia española a la que pertenecen los informadores es {}."
    - "De acuerdo con su manera de hablar, los informadores son de {}."
    - "{} es la región de la que provienen los informadores de esta entrevista."
    - "Se puede identificar la provincia de los informadores por su manera de hablar, que corresponde a {}."
    - "La provincia española a la que pertenecen los informadores es {}, debido a los rasgos lingüísticos presentes en su forma de hablar."
    - "Los informadores muestran un léxico y acento que sugieren su origen en {}."
    - "La provincia española a la que pertenecen los informadores es {}, debido a los características lingüísticas exhibidas durante la conversación."
    - "La provincia española a la que pertenecen los informadores es {}, ya que se han identificado rasgos lingüísticos característicos de esta región en su forma de hablar."
    - "Los informadores tienen un acento que sugiere que son de {}."
    - "La provincia española a la que pertenecen los informadores es {}, ya que se han manifestado características lingüísticas específicas de esta región en su forma de expresarse."
    - "La provincia española a la que pertenecen los informadores es {}, debido a la presencia de características lingüísticas específicas en su discurso."
    - "Su manera de hablar indica que los informadores son de {}."
    - "Los informadores entrevistados tienen el acento característico de {}."
    - "La provincia española a la que pertenecen los informadores es {}, debido a los características lingüísticas que manifestaron durante la entrevista."
    - "Los rasgos lingüísticos de los informadores sugieren que son de {} en España."
    - "Los informadores tienen rasgos lingüísticos típicos de {}."
    - "La provincia de {} es el lugar de origen de los informadores que participan en esta entrevista."
    - "Basándome en los rasgos lingüísticos exhibidos durante la conversación, puedo determinar que los informadores pertenecen a la provincia de {}."
    - "Los informadores utilizan expresiones propias de {}, indicando su procedencia."
    - "La provincia española a la que pertenecen los informadores es {}, según los rasgos lingüísticos presentes en su forma de hablar."
    - "Los informadores parecen ser nativos de {}, según su dialecto."
    - "La provincia española a la que pertenecen los informadores es {}, según los rasgos lingüísticos presentes en su conversación."
    - "Se puede deducir que los informadores son de {}, basándose en su forma de expresarse."
    - "Según su habla, los informadores son originarios de {}."
    - "Basándome en los rasgos lingüísticos presentes durante la conversación, puedo determinar que los informadores pertenecen a la provincia española de {}."
    - "Basándome en los rasgos lingüísticos manifestados durante la conversación, la provincia española a la que pertenecen los informadores es {}."
    - "Basándome en los rasgos lingüísticos que muestran durante la conversación, creo que la provincia española a la que pertenecen los informadores es {}."
    - "La provincia española a la que pertenecen los informadores es {}, ya que en su conversación se pueden observar características lingüísticas propias de esta región."
    - "La provincia española a la que pertenecen los informadores es {}, según los rasgos lingüísticos que muestran durante la conversación."
    - "La provincia española a la que pertenecen los informadores es {}, basado en los rasgos lingüísticos que muestran durante la conversación."
    - "Basándome en los rasgos lingüísticos presentes durante la conversación, puedo determinar con certeza que los informadores pertenecen a la provincia de {}."
    - "Basándome en los rasgos lingüísticos manifestados durante la conversación, creo que el informante proviene de la provincia de {}."
    - "La provincia española a la que pertenecen los informadores es {}, según los rasgos lingüísticos que han manifestado durante la conversación."
    - "Los informadores exhiben patrones lingüísticos asociados con {}."
    - "La provincia española a la que pertenecen los informadores es {}, según los rasgos lingüísticos que han manifestado durante la conversación. Su dialecto y uso del español reflejan una notable influencia gallega."
    - "La provincia española a la que pertenecen los informadores es {}, ya que se han manifestado rasgos lingüísticos específicos característicos de esta región en su forma de hablar."
    - "Basándome en los rasgos lingüísticos manifestados durante la conversación, creo que los informadores pertenecen a la provincia de {}."
    - "Basándome en los rasgos lingüísticos presentes durante la conversación, puedo determinar que la provincia española a la que pertenecen los informadores es {}."
    - "La provincia española a la que pertenecen los informadores es {}, ya que en su conversación se aprecian ciertos rasgos lingüísticos típicos de esta región."
    - "Basándome en los datos proporcionados, creo que los informadores son originarios de la provincia de {}."
    - "Basándome en los rasgos lingüísticos manifestados durante la conversación, puedo determinar con certeza que la provincia española a la que pertenecen los informadores es {}."
    - "La provincia española a la que pertenecen los informadores es {}, ya que su discurso refleja características lingüísticas específicas de esta comunidad autónoma."
    - "Basándome en los rasgos lingüísticos, puedo determinar que el informante proviene de la provincia de {}."
    - "La provincia española a la que pertenecen los informadores es {}, debido a los rasgos lingüísticos presentes en su discurso."
    - "Basándome en los rasgos lingüísticos que muestran los informadores durante la conversación, creo que la provincia española a la que pertenecen es {}."
    - "Basándome en los rasgos lingüísticos, creo que los informadores pertenecen a la provincia de {}."